# -*- coding: utf-8 -*-
"""binary_model_from_zero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11he7LK8a9-zTFcCVViHX5ZPqrpivoFvT

# Prótotipo do Modelo de Classificação Binário de Hanseníase

## Treinamento do Zero (sem pesos pré-treinados)
"""

import sys
import os

# Adiciona o diretório raiz do projeto ao path para importar utils
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(project_root)

# 1 - Importações
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import glob

from utils.models_to_pkl import save_model

# 2 - Criação de um modelo personalizado para entrada de 1 canal (escala de cinza)
# Como o ResNet50 espera 3 canais, vamos criar uma camada de entrada personalizada
input_layer = tf.keras.layers.Input(shape=(224, 224, 1))

# Converte de 1 canal para 3 canais replicando o canal de luminância
x = tf.keras.layers.Conv2D(3, (1, 1), padding='same', name='channel_expansion')(input_layer)

# Agora podemos usar o ResNet50 sem a camada de entrada original
base_model = tf.keras.applications.ResNet50(weights=None, include_top=False, input_tensor=x)

# 3 - Criando as Camadas Densas Personalizadas
x = base_model.output
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(256, activation='relu')(x)
predis = tf.keras.layers.Dense(1, activation='sigmoid')(x)

modelo_binario = tf.keras.Model(inputs=input_layer, outputs=predis)

# Tornando todas as camadas treináveis
for layer in modelo_binario.layers:
    layer.trainable = True

# 4 - Preparação do Dataset Customizado para arquivos .npy

def load_npy_dataset(data_dir, target_size=(224, 224)):
    """
    Carrega dataset de arquivos .npy organizados em subpastas por classe
    Os arquivos .npy agora contêm canal Y normalizado [0, 1]
    """
    images = []
    labels = []

    print(f"Procurando dados em: {os.path.abspath(data_dir)}")

    # Mapear classes para números
    class_names = ['leprosy', 'outros']
    class_to_idx = {name: idx for idx, name in enumerate(class_names)}

    for class_name in class_names:
        class_dir = os.path.join(data_dir, class_name)
        print(f"Verificando diretório: {os.path.abspath(class_dir)}")

        if not os.path.exists(class_dir):
            print(f"⚠️ Diretório não encontrado: {class_dir}")
            continue

        npy_files = glob.glob(os.path.join(class_dir, '*.npy'))
        print(f"Encontrados {len(npy_files)} arquivos .npy na classe '{class_name}'")

        for i, npy_file in enumerate(npy_files):
            try:
                # Carrega a imagem .npy (já normalizada [0, 1])
                img = np.load(npy_file)

                # Redimensiona para o tamanho alvo se necessário
                if img.shape != target_size:
                    img_resized = tf.image.resize(img[..., np.newaxis], target_size)
                    img_final = img_resized.numpy()
                else:
                    img_final = img[..., np.newaxis]

                images.append(img_final)
                labels.append(class_to_idx[class_name])

                # Mostra progresso a cada 100 imagens
                if (i + 1) % 100 == 0:
                    print(f"  Processadas {i + 1} imagens da classe '{class_name}'")

            except Exception as e:
                print(f"❌ Erro ao processar {npy_file}: {e}")
                continue

    print(f"Total de imagens carregadas: {len(images)}")
    return np.array(images), np.array(labels)

# Função simples para dividir dados em treino e validação
def simple_train_test_split(X, y, test_size=0.2, random_state=42):
    """
    Divisão simples de dados em treino e teste mantendo proporção das classes
    """
    np.random.seed(random_state)

    # Encontra índices para cada classe
    class_0_indices = np.where(y == 0)[0]
    class_1_indices = np.where(y == 1)[0]

    # Embaralha os índices
    np.random.shuffle(class_0_indices)
    np.random.shuffle(class_1_indices)

    # Calcula quantos exemplos de cada classe vão para teste
    n_test_class_0 = int(len(class_0_indices) * test_size)
    n_test_class_1 = int(len(class_1_indices) * test_size)

    # Divide os índices
    test_indices = np.concatenate([
        class_0_indices[:n_test_class_0],
        class_1_indices[:n_test_class_1]
    ])

    train_indices = np.concatenate([
        class_0_indices[n_test_class_0:],
        class_1_indices[n_test_class_1:]
    ])

    # Embaralha os índices finais
    np.random.shuffle(train_indices)
    np.random.shuffle(test_indices)

    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]

# Carrega o dataset
print("Carregando dataset...")

# Tenta diferentes caminhos possíveis
possible_paths = [
    'data/processed/train_images_binary',  # Caminho relativo da raiz do projeto
    '../data/processed/train_images_binary',  # Caminho relativo da pasta train
    '../../data/processed/train_images_binary'  # Caminho original
]

X, y = None, None
for path in possible_paths:
    try:
        print(f"Tentando caminho: {path}")
        X, y = load_npy_dataset(path)
        if len(X) > 0:
            print(f"✅ Dataset carregado com sucesso!")
            print(f"Total de imagens: {len(X)}")
            print(f"Distribuição das classes: {np.bincount(y)}")
            break
    except Exception as e:
        print(f"❌ Erro com caminho {path}: {e}")
        continue

if X is None or len(X) == 0:
    raise ValueError("Não foi possível carregar o dataset de nenhum dos caminhos testados!")

# Divide em treino e validação
X_train, X_val, y_train, y_val = simple_train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Formato dos dados de treino: {X_train.shape}")
print(f"Formato dos rótulos de treino: {y_train.shape}")
print(f"Formato dos dados de validação: {X_val.shape}")
print(f"Formato dos rótulos de validação: {y_val.shape}")

# Cria datasets do TensorFlow
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
train_dataset = train_dataset.batch(32).shuffle(1000)

val_dataset = tf.data.Dataset.from_tensor_slices((X_val, y_val))
val_dataset = val_dataset.batch(32)

# 5 - Compilando o Modelo
modelo_binario.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# 6 - Callbacks
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,
    patience=3,
    min_lr=1e-6,
    verbose=1
)

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)


# 7 - Treinamento
history = modelo_binario.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=40,
    callbacks=[reduce_lr, early_stopping]
)

# 8 - Salvando o Modelo e Histórico
save_model(modelo_binario, "modelo_binario_do_zero")

# Salva o histórico de treinamento separadamente
import pickle
os.makedirs('models', exist_ok=True)
with open('./models/modelo_binario_do_zero_history.pkl', 'wb') as f:
    pickle.dump(history.history, f)

# Salva informações adicionais do dataset
dataset_info = {
    'class_names': ['leprosy', 'outros'],
    'class_distribution': np.bincount(y).tolist(),
    'total_images': len(X),
    'train_images': len(X_train),
    'val_images': len(X_val),
    'input_shape': X_train.shape[1:],
    'num_classes': 2
}

with open('./models/modelo_binario_do_zero_info.pkl', 'wb') as f:
    pickle.dump(dataset_info, f)

print(f"✅ Modelo salvo em: ./models/modelo_binario_do_zero.pkl")
print(f"✅ Histórico salvo em: ./models/modelo_binario_do_zero_history.pkl")
print(f"✅ Informações do dataset salvas em: ./models/modelo_binario_do_zero_info.pkl")

# 9 - Avaliação Gráfica
accuracy = history.history["accuracy"]
val_accuracy = history.history["val_accuracy"]
loss = history.history["loss"]
val_loss = history.history["val_loss"]

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(accuracy, label="Acurácia de Treinamento")
plt.plot(val_accuracy, label="Acurácia de Validação")
plt.xlabel("Epochs")
plt.ylabel("Acurácia")
plt.legend()
plt.title("Evolução da Acurácia")

plt.subplot(1, 2, 2)
plt.plot(loss, label="Perda de Treinamento")
plt.plot(val_loss, label="Perda de Validação")
plt.xlabel("Epochs")
plt.ylabel("Perda")
plt.legend()
plt.title("Evolução da Perda")

plt.tight_layout()
plt.show()

# Análise de overfitting
overfitting = accuracy[-1] - val_accuracy[-1]
if overfitting > 0.1:
    print(f"⚠️ Possível overfitting detectado (diferença: {overfitting:.4f})")
else:
    print(f"✅ Modelo bem generalizado (diferença: {overfitting:.4f})")
