# -*- coding: utf-8 -*-
"""classsification_model_from_zero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iqMH1sqtGRt1wrMFw9Mh5OeXyLFO8ou

# Protótipo do modelo de classificação (Treinamento do Zero)
"""

import sys
import os

os.environ["TF_CUDNN_USE_AUTOTUNE"] = "0"
os.environ["TF_XLA_FLAGS"] = "--tf_xla_auto_jit=0"


# Adiciona o diretório raiz do projeto ao path para importar utils
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(project_root)
# 1 - Importações
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import glob

from utils.models_to_pkl import save_model

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)


# 2 - Criação de um modelo personalizado para entrada de 1 canal (escala de cinza)
# Como o ResNet50 espera 3 canais, vamos criar uma camada de entrada personalizada
input_layer = tf.keras.layers.Input(shape=(224, 224, 1))

tf.keras.mixed_precision.set_global_policy('float32')

# Converte de 1 canal para 3 canais replicando o canal de luminância
x = tf.keras.layers.Conv2D(3, (1, 1), padding='same', name='channel_expansion')(input_layer)

# Agora podemos usar o ResNet50 sem a camada de entrada original
base_model = tf.keras.applications.ResNet50(weights=None, include_top=False, input_tensor=x)

# 3 - Camadas densas personalizadas
x = base_model.output
x = tf.keras.layers.GlobalAveragePooling2D()(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dense(256, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(1024, activation='relu')(x)
x = tf.keras.layers.Dense(256, activation='relu')(x)
x = tf.keras.layers.Dense(128, activation='relu')(x)
predis = tf.keras.layers.Dense(7, activation='softmax')(x)

modelo_classificacao = tf.keras.Model(inputs=input_layer, outputs=predis)

# Tornando todas as camadas treináveis
for layer in modelo_classificacao.layers:
    layer.trainable = True

# 4 - Preparação do Dataset Customizado para arquivos .npy
def load_npy_classification_dataset(data_dir, target_size=(224, 224)):
    """
    Carrega dataset de arquivos .npy organizados em subpastas por classe para classificação multiclasse
    Os arquivos .npy agora contêm canal Y normalizado [0, 1]
    """
    images = []
    labels = []

    print(f"Procurando dados em: {os.path.abspath(data_dir)}")

    # Encontra todas as classes automaticamente
    class_names = []
    for item in os.listdir(data_dir):
        item_path = os.path.join(data_dir, item)
        if os.path.isdir(item_path):
            class_names.append(item)

    class_names.sort()  # Ordena para consistência
    class_to_idx = {name: idx for idx, name in enumerate(class_names)}

    print(f"Classes encontradas: {class_names}")
    print(f"Mapeamento classe->índice: {class_to_idx}")

    for class_name in class_names:
        class_dir = os.path.join(data_dir, class_name)
        print(f"Verificando diretório: {os.path.abspath(class_dir)}")

        if not os.path.exists(class_dir):
            print(f"⚠️ Diretório não encontrado: {class_dir}")
            continue

        npy_files = glob.glob(os.path.join(class_dir, '*.npy'))
        print(f"Encontrados {len(npy_files)} arquivos .npy na classe '{class_name}'")

        for i, npy_file in enumerate(npy_files):
            try:
                # Carrega a imagem .npy (já normalizada [0, 1])
                img = np.load(npy_file)

                # Redimensiona para o tamanho alvo se necessário
                if img.shape != target_size:
                    img_resized = tf.image.resize(img[..., np.newaxis], target_size)
                    img_final = img_resized.numpy()
                else:
                    img_final = img[..., np.newaxis]

                images.append(img_final)
                labels.append(class_to_idx[class_name])

                # Mostra progresso a cada 50 imagens
                if (i + 1) % 50 == 0:
                    print(f"  Processadas {i + 1} imagens da classe '{class_name}'")

            except Exception as e:
                print(f"❌ Erro ao processar {npy_file}: {e}")
                continue

    print(f"Total de imagens carregadas: {len(images)}")
    return np.array(images), np.array(labels), class_names

# Função simples para dividir dados em treino e validação mantendo proporção das classes
def simple_train_test_split_multiclass(X, y, test_size=0.2, random_state=42):
    """
    Divisão simples de dados em treino e teste mantendo proporção das classes para classificação multiclasse
    """
    np.random.seed(random_state)

    # Encontra índices para cada classe
    unique_classes = np.unique(y)
    train_indices = []
    test_indices = []

    for class_label in unique_classes:
        class_indices = np.where(y == class_label)[0]
        np.random.shuffle(class_indices)

        # Calcula quantos exemplos desta classe vão para teste
        n_test = int(len(class_indices) * test_size)

        test_indices.extend(class_indices[:n_test])
        train_indices.extend(class_indices[n_test:])

    # Embaralha os índices finais
    np.random.shuffle(train_indices)
    np.random.shuffle(test_indices)

    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]

# Carrega o dataset
print("Carregando dataset...")

# Tenta diferentes caminhos possíveis
possible_paths = [
    'data/Atlas_Dermatology/processed/train_images_classification',  # Caminho relativo da raiz do projeto
    '../data/Atlas_Dermatology/processed/train_images_classification',  # Caminho relativo da pasta train
    '../../data/Atlas_Dermatology/processed/train_images_classification'  # Caminho original
]

X, y, class_names = None, None, None
for path in possible_paths:
    try:
        print(f"Tentando caminho: {path}")
        X, y, class_names = load_npy_classification_dataset(path)
        if len(X) > 0:
            print(f"✅ Dataset carregado com sucesso!")
            print(f"Total de imagens: {len(X)}")
            print(f"Classes: {class_names}")
            print(f"Distribuição das classes: {np.bincount(y)}")
            break
    except Exception as e:
        print(f"❌ Erro com caminho {path}: {e}")
        continue

if X is None or len(X) == 0:
    raise ValueError("Não foi possível carregar o dataset de nenhum dos caminhos testados!")

# Divide em treino e validação
X_train, X_val, y_train, y_val = simple_train_test_split_multiclass(X, y, test_size=0.2, random_state=42)

print(f"Formato dos dados de treino: {X_train.shape}")
print(f"Formato dos rótulos de treino: {y_train.shape}")
print(f"Formato dos dados de validação: {X_val.shape}")
print(f"Formato dos rótulos de validação: {y_val.shape}")

# Converte rótulos para categorical (one-hot encoding)
y_train_categorical = tf.keras.utils.to_categorical(y_train, num_classes=len(class_names))
y_val_categorical = tf.keras.utils.to_categorical(y_val, num_classes=len(class_names))

# Cria datasets do TensorFlow
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train_categorical))
train_dataset = train_dataset.batch(8).shuffle(1000)

val_dataset = tf.data.Dataset.from_tensor_slices((X_val, y_val_categorical))
val_dataset = val_dataset.batch(8)

# 5 - Compilação do Modelo
modelo_classificacao.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 6 - Callbacks
reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.2,
    patience=3,
    min_lr=1e-6,
    verbose=1
)

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)

# 7 - Treinamento
history = modelo_classificacao.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=40,
    batch_size=8,
    callbacks=[reduce_lr, early_stopping]
)

# 8 - Salvando o modelo e histórico
save_model(modelo_classificacao, "modelo_classificacao_do_zero_atlas_dermatology")

# Salva o histórico de treinamento separadamente
import pickle
os.makedirs('models', exist_ok=True)
with open('./models/modelo_classificacao_do_zero_history.pkl', 'wb') as f:
    pickle.dump(history.history, f)

# Salva informações adicionais do dataset
dataset_info = {
    'class_names': class_names,
    'class_distribution': np.bincount(y).tolist(),
    'total_images': len(X),
    'train_images': len(X_train),
    'val_images': len(X_val),
    'input_shape': X_train.shape[1:],
    'num_classes': len(class_names)
}

with open('./models/modelo_classificacao_do_zero_info.pkl', 'wb') as f:
    pickle.dump(dataset_info, f)

print(f"✅ Modelo salvo em: ./models/modelo_classificacao_do_zero.pkl")
print(f"✅ Histórico salvo em: ./models/modelo_classificacao_do_zero_history.pkl")
print(f"✅ Informações do dataset salvas em: ./models/modelo_classificacao_do_zero_info.pkl")

# 9 - Avaliação Gráfica
accuracy = history.history["accuracy"]
val_accuracy = history.history["val_accuracy"]
loss = history.history["loss"]
val_loss = history.history["val_loss"]

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.plot(accuracy, label="Acurácia de Treinamento")
plt.plot(val_accuracy, label="Acurácia de Validação")
plt.xlabel("Epochs")
plt.ylabel("Acurácia")
plt.legend()
plt.title("Evolução da Acurácia")

plt.subplot(1, 3, 2)
plt.plot(loss, label="Perda de Treinamento")
plt.plot(val_loss, label="Perda de Validação")
plt.xlabel("Epochs")
plt.ylabel("Perda")
plt.legend()
plt.title("Evolução da Perda")

# Gráfico de distribuição das classes
plt.subplot(1, 3, 3)
class_counts = np.bincount(y)
plt.bar(range(len(class_names)), class_counts)
plt.xlabel("Classes")
plt.ylabel("Número de Imagens")
plt.title("Distribuição das Classes")
plt.xticks(range(len(class_names)), [name[:15] + '...' if len(name) > 15 else name for name in class_names], rotation=45)

plt.tight_layout()
plt.show()

print(f"\n📊 Resumo do Treinamento:")
print(f"Classes: {len(class_names)}")
print(f"Total de imagens: {len(X)}")
print(f"Imagens de treino: {len(X_train)}")
print(f"Imagens de validação: {len(X_val)}")
print(f"Acurácia final de treino: {accuracy[-1]:.4f}")
print(f"Acurácia final de validação: {val_accuracy[-1]:.4f}")
print(f"Classes: {class_names}")

# Análise de overfitting
overfitting = accuracy[-1] - val_accuracy[-1]
if overfitting > 0.1:
    print(f"⚠️ Possível overfitting detectado (diferença: {overfitting:.4f})")
else:
    print(f"✅ Modelo bem generalizado (diferença: {overfitting:.4f})")
